DB:
  dbname: nativeSources
  collection:
    name : sourceABN
    docfield: record

HOST:
  authDB: admin
  password: null
  port: 29017
  server: sb-udb5.swissbib.unibas.ch
  user: null

Solr:
  host: http://sb-us18.swissbib.unibas.ch:8080/solr/green/select

